using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;
using System.Xml.Linq;

namespace Sportacus
{
    public partial class EventSelection : Form
    {
        Main.Student student;
        EventEntryForm.Event EventDetails;


        public EventSelection(Main.Student studentDetails, EventEntryForm.Event eventDetails)
        {
            InitializeComponent();
            lblEventName.Text = eventDetails.eventName;
            student = studentDetails;
            EventDetails = eventDetails;
        }

        private void EventSelection_Load(object sender, EventArgs e)
        {

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btnJoin_Click(object sender, EventArgs e)
        {
            //Find which radio button is selected
            var checkedButton = panelHeats.Controls.OfType<RadioButton>().FirstOrDefault(r => r.Checked);
            Close();

            try
            {
                // If the file exists, then add elements to the provided XML file
                XDocument xmlDoc = XDocument.Load("StudentData.xml");

                xmlDoc.Element("Students").Add(new XElement("Student", new XElement("firstName", student.firstName), new XElement("lastName", student.lastName), new XElement("house", student.house), new XElement("yearLevel", Convert.ToString(student.yearLevel)), new XElement("eventName", EventDetails.eventName), new XElement("heat", checkedButton.Text), new XElement("username", student.username)));

                xmlDoc.Save("StudentData.xml");
            }

            catch
            {
                // If the file doesn't exist, create a new structured StudentData XML file
                XmlWriterSettings settings = new XmlWriterSettings();
                    settings.Indent = true;
                XmlWriter writer = XmlWriter.Create(@"StudentData.xml", settings);

                writer.WriteStartDocument();
                writer.WriteComment("This file is generated by the program");

                writer.WriteStartElement("Students");
                writer.WriteEndDocument();
                writer.Flush();
                writer.Close();

                XDocument xmlDoc = XDocument.Load("StudentData.xml");

                xmlDoc.Element("Students").Add(new XElement("Student", new XElement("firstName", student.firstName), new XElement("lastName", student.lastName), new XElement("house", student.house), new XElement("yearLevel", Convert.ToString(student.yearLevel)), new XElement("eventName", EventDetails.eventName), new XElement("heat", checkedButton.Text), new XElement("username", student.username)));

                xmlDoc.Save("StudentData.xml");
            }
        }
    }
}