using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;

namespace Sportacus
{
    public partial class EventSelection : Form
    {
        Main.Student student;
        EventEntryForm.Event EventDetails;

        public EventSelection(Main.Student studentDetails, EventEntryForm.Event eventDetails)
        {
            InitializeComponent();
            lblEventName.Text = eventDetails.eventName;
            student = studentDetails;
            EventDetails = eventDetails;
        }

        private void EventSelection_Load(object sender, EventArgs e)
        {

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btnJoin_Click(object sender, EventArgs e)
        {
            //Find which radio button is selected
            var checkedButton = panelHeats.Controls.OfType<RadioButton>().FirstOrDefault(r => r.Checked);
            Console.WriteLine(checkedButton.Text);
            Close();


            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            XmlWriter writer = XmlWriter.Create(@"StudentData.xml", settings);

            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program");

            writer.WriteStartElement("Students");
            writer.WriteStartElement("Student");
            writer.WriteElementString("studentFirstName", student.firstName);
            writer.WriteElementString("studentLastName", student.lastName);
            writer.WriteElementString("House", student.house);
            writer.WriteElementString("yearLevel", Convert.ToString(student.yearLevel));
            writer.WriteElementString("event", EventDetails.eventName);
            writer.WriteElementString("Heat", checkedButton.Text);
            writer.WriteEndElement();
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();


        }
    }
}
