using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml;

namespace Sportacus
{
    public partial class EventSelection : Form
    {

        public EventSelection(Form1.Student studentDetails, EventEntryForm.Event eventDetails)
        {
            InitializeComponent();
            lblEventName.Text = eventDetails.eventName;
        }

        private void EventSelection_Load(object sender, EventArgs e)
        {

        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void btnJoin_Click(object sender, EventArgs e)
        {
            //Find which radio button is selected
            var checkedButton = panelHeats.Controls.OfType<RadioButton>().FirstOrDefault(r => r.Checked);
            Console.WriteLine(checkedButton.Text);
            Close();


            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            XmlWriter writer = XmlWriter.Create(@"StudentData.xml", settings);

            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program");

            writer.WriteStartElement("Students");
            writer.WriteStartElement("Student");
            writer.WriteAttributeString("Heat", checkedButton.Text);
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();


        }
    }
}
